from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request model for the /chat endpoint."""
    question: str = Field(
        ...,
        min_length=3,
        description="The user's query about the Agentic AI eBook.",
        json_schema_extra={"example": "What is the ReAct pattern in Agentic AI systems?"}
    )


class RetrievedChunk(BaseModel):
    """Representation of a retrieved context chunk with metadata and relevance score."""
    content: str = Field(..., description="Text content of the retrieved document chunk.")
    metadata: Dict[str, Any] = Field(
        ...,
        description="Metadata dictionary containing page number, source document, and chunk ID."
    )
    relevance_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized relevance similarity score between 0.0 and 1.0."
    )


class ChatResponse(BaseModel):
    """Response model returned by the /chat endpoint."""
    answer: str = Field(..., description="Grounded answer generated by the RAG pipeline.")
    retrieved_chunks: List[RetrievedChunk] = Field(
        default_factory=list,
        description="List of context chunks used to formulate the answer."
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall confidence score of the grounded answer based on chunk relevance."
    )


class HealthResponse(BaseModel):
    """Health check status model."""
    status: str = Field(..., description="Service status ('ok' or 'degraded').")
    vector_store: str = Field(..., description="Active vector store type (e.g., ChromaDB, Pinecone).")
    embedding_provider: str = Field(..., description="Active embedding provider name.")
    llm_model: str = Field(..., description="Active LLM model name.")
    indexed_documents_count: Optional[int] = Field(
        default=None,
        description="Number of ingested vector chunks in the store."
    )
